apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
  - name: source-url
  - name: source-revision
  tasks:
  - name: test
    params:
    - name: source-url
      value: $(params.source-url)
    - name: source-revision
      value: $(params.source-revision)
    taskSpec:
      params:
      - name: source-url
      - name: source-revision
      steps:
        - name: test
          image: gradle
          script: |-
            set -ex
            cd `mktemp -d`
            wget -qO- $(params.source-url) | tar xvz -m
            ./mvnw test
