# This is a basic workflow to help you get started with Actions

name: run

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Pull cli
        run: |
          brew install pivotal/tap/pivnet-cli
          whoami
          PRODUCT_ID=1190781; #linux
          pivnet download-product-files --product-slug='tanzu-application-platform' --release-version='1.1.1' --product-file-id=$PRODUCT_ID
          mkdir tanzu
          tar -xvf "tanzu-framework-$PRODUCT_ID-amd64.tar" -C tanzu
          export TANZU_CLI_NO_INIT=true
          cd tanzu
          sudo install "cli/core/v0.11.2/tanzu-core-$PRODUCT_ID_amd64" /usr/local/bin/tanzu
          tanzu version

          tanzu plugin install --local cli all
          tanzu plugin list
          cd ..
      